### ISSUE TITLE
Need to make own version of cloudant lib

### ISSUE THREAD

**Issue by gadamc** [nEDM-TUM/HimbeereCouch#2]
Unless you plan on dealing with the update of the `cloudant` library that is coming next year (which will deprecate and remove the 0.5.x version from PyPI) you should probably consider rolling out your own version of the 0.5.x library to PyPI ("mgm-cloudant" ??). 

Otherwise, when IBM deprecates that library and removes it from PyPI, everything will break.  The new version of the `cloudant` library (2.0.x) will be a significant departure from the current library.

**Comment by mgmarino** [comment]
Thanks, we will reduce the impact by limiting the dependency to nEDM-TUM/Python-Slow-Control and forking our own version of `cloudant`

**Comment by mgmarino** [comment]
This was taken care of by:
- forking the cloudant-python repo and tagging an 'nedm' version
- updating the setup.py/requirements.txt files to point to this version.
